[package]
name = "sample"
version = "0.0.0"
edition = "2018"

[dependencies]
windows = { path = "../../windows-rs" }
bindings = { path = "bindings" }
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
