[package]
name = "bindings"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
windows = "0.17.0"
windows-app = "0.17.0"

[build-dependencies]
windows = "0.17.0"
windows-app = "0.17.0"
