[package]
name = "skeleton_bindings"
version = "0.0.0"
edition = "2018"

[dependencies]
windows = "0.12.0"
windows-app = { git = "https://github.com/microsoft/windows-app-rs" }

[build-dependencies]
windows = "0.12.0"
windows-app = { git = "https://github.com/microsoft/windows-app-rs" }