[package]
name = "sample"
version = "0.0.0"
edition = "2018"

[dependencies.windows]
path = "/git/windows-rs"
features = [
    "std",
    "Win32_System_Com",
    "Win32_Foundation",
    "Win32_Globalization",
]
