[package]
name = "bindings"
version = "0.0.0"
edition = "2018"

[dependencies]
windows = { path = "/git/windows-rs", features = ["build"] }

[build-dependencies]
windows = { path = "/git/windows-rs", features = ["build"] }
