[package]
name = "sample"
version = "0.0.0"
edition = "2018"

[dependencies]
futures = "0.3.5"

[dependencies.windows]
version = "0.24"
features = [
    "Media_Ocr", 
    "Graphics_Imaging", 
    "Storage_Streams", 
    "Foundation",
]
