[package]
name = "sample"
version = "0.0.0"
edition = "2018"

[dependencies.windows]
#path = "/git/windows-rs"
path = "/git/windows-rs"
features = [
    "build",
    "ApplicationModel_Core",
    "UI_Core",
    "Win32_System_Com",
]
