[package]
name = "sample"
version = "0.0.0"
edition = "2018"

[dependencies.windows]
#version = "0.26"
version = "0.26"
features = [
    "build",
    "ApplicationModel_Core",
    "UI_Core",
    "Win32_System_Com",
]
