[package]
name = "webview2"
version = "0.0.0"
edition = "2018"

[dependencies]
windows = "0.13.0"
bindings = { package = "webview2_bindings", path = "bindings" }
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
