[package]
name = "sample"
version = "0.0.0"
edition = "2018"

[dependencies.windows-sys]
git = "https://github.com/microsoft/windows-rs"
features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
]
