[package]
name = "sample"
version = "0.0.0"
edition = "2018"

[dependencies.windows]
#git = "https://github.com/microsoft/windows-rs"
path = "/git/windows-rs"
features = [
    "build",
    "ApplicationModel_Activation",
    "Win32_System_Com",
    "UI_Xaml_Controls",
    "UI_Xaml",
]
