[package]
name = "sample"
version = "0.0.0"
edition = "2018"

[dependencies.windows]
version = "0.24"
features = [
    "build",
    "ApplicationModel_Activation",
    "Win32_System_Com",
    "UI_Xaml_Controls",
    "UI_Xaml",
]
