[package]
name = "bindings"
version = "0.0.0"
edition = "2018"

[dependencies]
windows = { version = "0.18", features = ["raw_dylib"] }

[build-dependencies]
windows = { version = "0.18", features = ["raw_dylib"] }
