[package]
name = "bindings"
version = "0.0.0"
edition = "2018"

[dependencies]
windows = { git = "https://github.com/microsoft/windows-rs", features = ["raw_dylib"] }

[build-dependencies]
windows = { git = "https://github.com/microsoft/windows-rs", features = ["raw_dylib"] }
