name: Build and Test

on:
  pull_request:
  push:
    branches:
      - master

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: windows-latest
          rust: stable
          other: x86_64-pc-windows-msvc
        - os: windows-latest
          rust: 1.51.0
          other: x86_64-pc-windows-msvc
        - os: windows-latest
          rust: nightly
          other: x86_64-pc-windows-msvc
        - os: windows-latest
          rust: stable
          other: i686-pc-windows-msvc
        - os: windows-latest
          rust: nightly
          other: i686-pc-windows-msvc
    steps:
    - uses: actions/checkout@v2
    - run: rustup update --no-self-update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
    - run: rustup target add ${{ matrix.other }}

    - name: windows build (root workspace)
      shell: pwsh
      run: |
        Get-ChildItem -Directory | ForEach-Object {
          $toml_path = [IO.Path]::Combine($_, "Cargo.toml");
          
          if( (Test-Path $toml_path) -And (Get-Content($toml_path) | ForEach-Object {
            $_ -imatch "[workspace]" })
          ) { $_ }
        } | ForEach-Object {
          Push-Location $_;
          Write-Output "Building $(Get-Location)";

          cargo test --all --target ${{ matrix.other }};

          Pop-Location;
        }

  cargo_fmt:
    runs-on: windows-latest
    name: Check cargo formatting
    steps:
    - uses: actions/checkout@v2
    - name: Run cargo fmt
      run: cargo fmt --all -- --check

  cargo_doc:
    runs-on: windows-latest
    name: Check cargo docs
    steps:
    - uses: actions/checkout@v2
    - name: Run cargo doc
      run: cargo doc --no-deps --workspace