name: Build and Test

on:
  pull_request:
  push:
    branches:
      - master

env:
  RUSTFLAGS: -Dwarnings

jobs:
  gen_matrix:
    name: Generate crate matrix
    runs-on: windows-latest 
    outputs:
      crate: ${{ steps.gen_matrix.outputs.crate }}
    steps:
    - uses: actions/checkout@v2
    - id: gen_matrix
      name: Enumerate crates
      shell: pwsh
      run: |
        function Get-BuildableCratePaths {
            Get-ChildItem -Directory | ForEach-Object {
              if(Test-Path ([IO.Path]::Combine($_, "Cargo.toml"))) {
                  [IO.Path]::GetRelativePath(".", $_.FullName)
              } else {
                Push-Location $_
                Get-BuildableCratePaths
                Pop-Location
              }
            }
        }
        $crates = Get-BuildableCratePaths | ConvertTo-Json -Compress -AsArray
        "debug ...=crate::$crates"
        "::set-output name=crate::$crates"

  test:
    name: Build and test crate
    runs-on: ${{ matrix.os }}
    needs:
      - gen_matrix
    strategy:
      matrix:
        include:
        - crate: ${{fromJson(needs.gen_matrix.outputs.crate)}}
        - os: windows-latest
          rust: stable
          other: x86_64-pc-windows-msvc
        - os: windows-latest
          rust: 1.51.0
          other: x86_64-pc-windows-msvc
        - os: windows-latest
          rust: nightly
          other: x86_64-pc-windows-msvc
        - os: windows-latest
          rust: stable
          other: i686-pc-windows-msvc
        - os: windows-latest
          rust: nightly
          other: i686-pc-windows-msvc
    steps:
    - name: placebo
      working-directory: ${{ matrix.crate }}
      run: dir
